### ISSUE TITLE
nothing happens when connecting to redis slave

### ISSUE THREAD

**Issue by patsevanton** [leonchen83/redis-rdb-cli#85]
**Ask a question**
nothing happens when connecting to redis slave

**Describe the bug**
```
rst -s redis://rc1b-yyy.mdb.cloud.net:6379?authPassword=xxxx -m redis://c-yyyyy.rw.mdb.cloud.net:6379?authPassword=xxxx -r
or
rdt -b rediss://rc1b-yyy.mdb.cloud.net:6379?authPassword=xxx -o recsys-inference.rdb
```

**To Reproduce**
i think Reproduce for specific situation

**Expected behavior**

**Screenshots**

**Version(run `rdt --version` or `rdt -V` and paste the information):**  
```
./rdt --version
redis rdb cli: v0.9.6 (f3fba93cb9f304bdb5ffbe735e000065c1390c27: 2024-07-15T12:52:27+0000)
home: /root/redis-rdb-cli/bin/..
java version: 11.0.25, vendor: Ubuntu
java home: /usr/lib/jvm/java-11-openjdk-amd64
default locale: en, platform encoding: UTF-8
os name: Linux, version: 6.8.0-49-generic, arch: amd64
```
**Additional context**
managed redis 7.2

i can connect only to 1 redis host in managed redis.

How enable debug log?

I test https://github.com/yannh/redis-dump-go

```
./redis-dump-go -host rc1b-yyy.mdb.cloud.net -port 6379 -batchSize 1000000 -n 1000 > recsys-inference.rdb
Database 0: 4900 element dumped
```
redis-dump-go work

**Comment by leonchen83** [comment]
you can send related log in your `/root/redis-rdb-cli/log/redis-rdb-cli.log` to here.

**Comment by patsevanton** [comment]
cat /root/redis-rdb-cli/log/redis-rdb-cli.log
```
2024-12-10 03:00:27,786 INFO c.m.r.r.RedisSocketReplicator [main] connected to redis-server[rc1b-yyy.mdb.cloud.net:6379]
2024-12-10 03:00:27,790 INFO c.m.r.r.RedisSocketReplicator [main] AUTH #xxxxxxxxxxxxxx
2024-12-10 03:01:27,833 INFO c.m.r.r.RedisSocketReplicator [main] socket closed. redis-server[rc1b-yyy.mdb.cloud.net:6379]
2024-12-10 03:01:27,833 INFO c.m.r.r.RedisSocketReplicator [main] reconnecting to redis-server[rc1b-yyy.mdb.cloud.net:6379]. retry times:1
2024-12-10 03:01:28,851 INFO c.m.r.r.RedisSocketReplicator [main] connected to redis-server[rc1b-yyy.mdb.cloud.net:6379]
2024-12-10 03:01:28,852 INFO c.m.r.r.RedisSocketReplicator [main] AUTH #xxxxxxxxxxxxxx
```

**Comment by leonchen83** [comment]
what version is your source redis?
for now redis-rdb-cli not yet support redis-7.4.x and source redis **MUST** support `PSYNC` or `SYNC` command. 
if not. you chould change parameter in `/root/redis-rdb-cli/conf/redis-rdb-cli.conf`
`enable_scan=true`

after above, use following cli command to execute
`rdt -b redis://rc1b-yyy.mdb.cloud.net:6379?authPassword=xxx -o recsys-inference.rdb`

**Comment by patsevanton** [comment]
managed redis 7.2

i changed in config
```
source_default_truststore=true
target_default_truststore=true
```
command:
```
./rdt -b rediss://rc1b-yyyyyy.mdb.cloud.net:6379?authPassword=xxxxxxxxx -o recsys-inference.rdb

java.net.SocketException: Socket closed
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:183)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:484)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:478)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1511)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
	at java.base/sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:926)
	at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1296)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at com.moilioncircle.redis.replicator.io.RedisOutputStream.flush(RedisOutputStream.java:56)
	at com.moilioncircle.redis.replicator.RedisSocketReplicator.send(RedisSocketReplicator.java:331)
	at com.moilioncircle.redis.replicator.RedisSocketReplicator.auth(RedisSocketReplicator.java:211)
	at com.moilioncircle.redis.replicator.RedisSocketReplicator.establishConnection(RedisSocketReplicator.java:192)
	at com.moilioncircle.redis.replicator.RedisSocketReplicator$RedisSocketReplicatorRetrier.connect(RedisSocketReplicator.java:413)
	at com.moilioncircle.redis.replicator.AbstractReplicatorRetrier.retry(AbstractReplicatorRetrier.java:46)
	at com.moilioncircle.redis.replicator.RedisSocketReplicator.open(RedisSocketReplicator.java:123)
	at com.moilioncircle.redis.rdb.cli.ext.XRedisReplicator.open(XRedisReplicator.java:253)
	at com.moilioncircle.redis.rdb.cli.cmd.XRdt.call(XRdt.java:190)
	at com.moilioncircle.redis.rdb.cli.cmd.XRdt.call(XRdt.java:50)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at com.moilioncircle.redis.rdb.cli.Rdt.main(Rdt.java:28)

```

log
```
cat /root/redis-rdb-cli/log/redis-rdb-cli.log
2024-12-10 03:14:42,670 INFO c.m.r.r.RedisSocketReplicator [main] connected to redis-server[rc1b-yyy.mdb.cloud.net:6379]
2024-12-10 03:14:42,675 INFO c.m.r.r.RedisSocketReplicator [main] AUTH #xxxxxxxxxxxxxx
2024-12-10 03:15:42,759 INFO c.m.r.r.RedisSocketReplicator [main] socket closed. redis-server[rc1b-yyy.mdb.cloud.net:6379]
2024-12-10 03:15:42,759 INFO c.m.r.r.RedisSocketReplicator [main] reconnecting to redis-server[rc1b-yyy.mdb.cloud.net:6379]. retry times:1
2024-12-10 03:15:43,776 INFO c.m.r.r.RedisSocketReplicator [main] connected to redis-server[rc1b-yyy.mdb.cloud.net:6379]
2024-12-10 03:15:43,776 INFO c.m.r.r.RedisSocketReplicator [main] AUTH #xxxxxxxxxxxxxx
2024-12-10 03:16:43,840 INFO c.m.r.r.RedisSocketReplicator [main] socket closed. redis-server[rc1b-yyy.mdb.cloud.net:6379]
2024-12-10 03:16:43,840 INFO c.m.r.r.RedisSocketReplicator [main] reconnecting to redis-server[rc1b-yyy.mdb.cloud.net:6379]. retry times:2
2024-12-10 03:16:44,858 INFO c.m.r.r.RedisSocketReplicator [main] connected to redis-server[rc1b-yyy.mdb.cloud.net:6379]
2024-12-10 03:16:44,858 INFO c.m.r.r.RedisSocketReplicator [main] AUTH #xxxxxxxxxxxxxx
2024-12-10 03:17:44,866 INFO c.m.r.r.RedisSocketReplicator [main] socket closed. redis-server[rc1b-yyy.mdb.cloud.net:6379]
2024-12-10 03:17:44,866 INFO c.m.r.r.RedisSocketReplicator [main] reconnecting to redis-server[rc1b-yyy.mdb.cloud.net:6379]. retry times:3
2024-12-10 03:17:45,884 INFO c.m.r.r.RedisSocketReplicator [main] connected to redis-server[rc1b-yyy.mdb.cloud.net:6379]
2024-12-10 03:17:45,885 INFO c.m.r.r.RedisSocketReplicator [main] AUTH #xxxxxxxxxxxxxx
2024-12-10 03:18:45,948 INFO c.m.r.r.RedisSocketReplicator [main] socket closed. redis-server[rc1b-yyy.mdb.cloud.net:6379]
2024-12-10 03:18:45,948 INFO c.m.r.r.RedisSocketReplicator [main] reconnecting to redis-server[rc1b-yyy.mdb.cloud.net:6379]. retry times:4
2024-12-10 03:18:46,965 INFO c.m.r.r.RedisSocketReplicator [main] connected to redis-server[rc1b-yyy.mdb.cloud.net:6379]
2024-12-10 03:18:46,966 INFO c.m.r.r.RedisSocketReplicator [main] AUTH #xxxxxxxxxxxxxx
2024-12-10 03:19:47,029 INFO c.m.r.r.RedisSocketReplicator [main] socket closed. redis-server[rc1b-yyy.mdb.cloud.net:6379]
2024-12-10 03:19:47,029 INFO c.m.r.r.RedisSocketReplicator [main] reconnecting to redis-server[rc1b-yyy.mdb.cloud.net:6379]. retry times:5
2024-12-10 03:19:48,030 INFO c.m.r.r.RedisSocketReplicator [main] socket closed. redis-server[rc1b-yyy.mdb.cloud.net:6379]
```

**Comment by leonchen83** [comment]
is `redis-dump-go` and `redis-rdb-cli` in the same machine?
It seems to be an issue with creating an SSL connection. Or the firewall is forcibly blocking the machine running redis-rdb-cli from accessing `rc1b-yyy.mdb.cloud.net:6379`

**Comment by patsevanton** [comment]
redis-dump-go and redis-rdb-cli in the same machine

command
```
./rdt -b redis://rc1b-yyy.mdb.cloud.net:6379?authPassword=xxxxxxxxx -o recsys-inference.rdb
```

cat /root/redis-rdb-cli/log/redis-rdb-cli.log
```
2024-12-10 03:38:09,876 INFO c.m.r.r.RedisSocketReplicator [main] connected to redis-server[rc1b-yyy.mdb.cloud.net:6379]
2024-12-10 03:38:09,876 INFO c.m.r.r.RedisSocketReplicator [main] AUTH #xxxxxxxxxxxxxx
2024-12-10 03:38:09,890 INFO c.m.r.r.RedisSocketReplicator [main] OK
2024-12-10 03:38:09,890 INFO c.m.r.r.RedisSocketReplicator [main] PING
2024-12-10 03:38:09,903 INFO c.m.r.r.RedisSocketReplicator [main] PONG
2024-12-10 03:38:09,903 INFO c.m.r.r.RedisSocketReplicator [main] REPLCONF listening-port 55512
2024-12-10 03:38:09,917 INFO c.m.r.r.RedisSocketReplicator [main] NOPERM User default has no permissions to run the 'replconf' command
2024-12-10 03:38:09,917 WARN c.m.r.r.RedisSocketReplicator [main] [REPLCONF listening-port 55512] failed. NOPERM User default has no permissions to run the 'replconf' command
2024-12-10 03:38:09,917 INFO c.m.r.r.RedisSocketReplicator [main] REPLCONF ip-address 10.236.91.9
2024-12-10 03:38:09,931 INFO c.m.r.r.RedisSocketReplicator [main] NOPERM User default has no permissions to run the 'replconf' command
2024-12-10 03:38:09,931 WARN c.m.r.r.RedisSocketReplicator [main] [REPLCONF ip-address 10.236.91.9] failed. NOPERM User default has no permissions to run the 'replconf' command
2024-12-10 03:38:09,931 INFO c.m.r.r.RedisSocketReplicator [main] REPLCONF capa eof
2024-12-10 03:38:09,945 INFO c.m.r.r.RedisSocketReplicator [main] NOPERM User default has no permissions to run the 'replconf' command
2024-12-10 03:38:09,945 WARN c.m.r.r.RedisSocketReplicator [main] [REPLCONF capa eof] failed. NOPERM User default has no permissions to run the 'replconf' command
2024-12-10 03:38:09,945 INFO c.m.r.r.RedisSocketReplicator [main] REPLCONF capa psync2
2024-12-10 03:38:09,959 INFO c.m.r.r.RedisSocketReplicator [main] NOPERM User default has no permissions to run the 'replconf' command
2024-12-10 03:38:09,959 WARN c.m.r.r.RedisSocketReplicator [main] [REPLCONF capa psync2] failed. NOPERM User default has no permissions to run the 'replconf' command
2024-12-10 03:38:09,959 INFO c.m.r.r.RedisSocketReplicator [main] REPLCONF rdb-only 1
2024-12-10 03:38:09,973 INFO c.m.r.r.RedisSocketReplicator [main] NOPERM User default has no permissions to run the 'replconf' command
2024-12-10 03:38:09,973 WARN c.m.r.r.RedisSocketReplicator [main] [REPLCONF rdb-only 1] failed. NOPERM User default has no permissions to run the 'replconf' command
2024-12-10 03:38:09,973 INFO c.m.r.r.RedisSocketReplicator [main] PSYNC ? -1
2024-12-10 03:38:09,987 INFO c.m.r.r.RedisSocketReplicator [main] NOPERM User default has no permissions to run the 'psync' command
2024-12-10 03:38:09,987 INFO c.m.r.r.RedisSocketReplicator [main] SYNC
2024-12-10 03:38:10,002 INFO c.m.r.r.RedisSocketReplicator [main] socket closed. redis-server[rc1b-yyy.mdb.cloud.net:6379]
2024-12-10 03:38:10,002 INFO c.m.r.r.RedisSocketReplicator [main] reconnecting to redis-server[rc1b-yyy.mdb.cloud.net:6379]. retry times:1
```

**Comment by leonchen83** [comment]
> redis-dump-go and redis-rdb-cli in the same machine
> 
> command
> 
> ```
> ./rdt -b redis://rc1b-yyy.mdb.cloud.net:6379?authPassword=xxxxxxxxx -o recsys-inference.rdb
> ```
> 
> cat /root/redis-rdb-cli/log/redis-rdb-cli.log
> 
> ```
> 2024-12-10 03:38:09,876 INFO c.m.r.r.RedisSocketReplicator [main] connected to redis-server[rc1b-yyy.mdb.cloud.net:6379]
> 2024-12-10 03:38:09,876 INFO c.m.r.r.RedisSocketReplicator [main] AUTH #xxxxxxxxxxxxxx
> 2024-12-10 03:38:09,890 INFO c.m.r.r.RedisSocketReplicator [main] OK
> 2024-12-10 03:38:09,890 INFO c.m.r.r.RedisSocketReplicator [main] PING
> 2024-12-10 03:38:09,903 INFO c.m.r.r.RedisSocketReplicator [main] PONG
> 2024-12-10 03:38:09,903 INFO c.m.r.r.RedisSocketReplicator [main] REPLCONF listening-port 55512
> 2024-12-10 03:38:09,917 INFO c.m.r.r.RedisSocketReplicator [main] NOPERM User default has no permissions to run the 'replconf' command
> 2024-12-10 03:38:09,917 WARN c.m.r.r.RedisSocketReplicator [main] [REPLCONF listening-port 55512] failed. NOPERM User default has no permissions to run the 'replconf' command
> 2024-12-10 03:38:09,917 INFO c.m.r.r.RedisSocketReplicator [main] REPLCONF ip-address 10.236.91.9
> 2024-12-10 03:38:09,931 INFO c.m.r.r.RedisSocketReplicator [main] NOPERM User default has no permissions to run the 'replconf' command
> 2024-12-10 03:38:09,931 WARN c.m.r.r.RedisSocketReplicator [main] [REPLCONF ip-address 10.236.91.9] failed. NOPERM User default has no permissions to run the 'replconf' command
> 2024-12-10 03:38:09,931 INFO c.m.r.r.RedisSocketReplicator [main] REPLCONF capa eof
> 2024-12-10 03:38:09,945 INFO c.m.r.r.RedisSocketReplicator [main] NOPERM User default has no permissions to run the 'replconf' command
> 2024-12-10 03:38:09,945 WARN c.m.r.r.RedisSocketReplicator [main] [REPLCONF capa eof] failed. NOPERM User default has no permissions to run the 'replconf' command
> 2024-12-10 03:38:09,945 INFO c.m.r.r.RedisSocketReplicator [main] REPLCONF capa psync2
> 2024-12-10 03:38:09,959 INFO c.m.r.r.RedisSocketReplicator [main] NOPERM User default has no permissions to run the 'replconf' command
> 2024-12-10 03:38:09,959 WARN c.m.r.r.RedisSocketReplicator [main] [REPLCONF capa psync2] failed. NOPERM User default has no permissions to run the 'replconf' command
> 2024-12-10 03:38:09,959 INFO c.m.r.r.RedisSocketReplicator [main] REPLCONF rdb-only 1
> 2024-12-10 03:38:09,973 INFO c.m.r.r.RedisSocketReplicator [main] NOPERM User default has no permissions to run the 'replconf' command
> 2024-12-10 03:38:09,973 WARN c.m.r.r.RedisSocketReplicator [main] [REPLCONF rdb-only 1] failed. NOPERM User default has no permissions to run the 'replconf' command
> 2024-12-10 03:38:09,973 INFO c.m.r.r.RedisSocketReplicator [main] PSYNC ? -1
> 2024-12-10 03:38:09,987 INFO c.m.r.r.RedisSocketReplicator [main] NOPERM User default has no permissions to run the 'psync' command
> 2024-12-10 03:38:09,987 INFO c.m.r.r.RedisSocketReplicator [main] SYNC
> 2024-12-10 03:38:10,002 INFO c.m.r.r.RedisSocketReplicator [main] socket closed. redis-server[rc1b-yyy.mdb.cloud.net:6379]
> 2024-12-10 03:38:10,002 INFO c.m.r.r.RedisSocketReplicator [main] reconnecting to redis-server[rc1b-yyy.mdb.cloud.net:6379]. retry times:1
> ```

the root cause is there is NOPERM to run PSYNC and and REPLCONF command
so you can change parameter `enable_scan=true` and rerun `rdt -b redis://rc1b-yyy.mdb.cloud.net:6379?authPassword=xxxxxxxxx -o recsys-inference.rdb`

**Comment by leonchen83** [comment]
or change a user that has `PSYNC` and `REPLCONF` permissions.
`./rdt -b redis://rc1b-yyy.mdb.cloud.net:6379?authUser=xxx&authPassword=xxxxxxxxx -o recsys-inference.rdb`

**Comment by patsevanton** [comment]
is it possible to make errors appear when running the rdt command ?

**Comment by leonchen83** [comment]
most exception are appeared in command ,but `NOPERM ` is a WARN message, that shoud be check log file

**Comment by patsevanton** [comment]
I think it's worth adding that if there is no output, it's worth looking at the log `redis-rdb-cli/log/redis-rdb-cli.log`

**Comment by leonchen83** [comment]
Add `troubleshooting` to README.md is a good idea!
